name: CI-workflow
on: 
  push:
    branches: [ "curso-github-actions" ]

  workflow_dispatch:

jobs:
  workflow-ejemplo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hola mundo
        run: |
            python bienvenidos.py
